export const API_URL = 'api';
export const EMAIL_AVAILABILITY = '/users';
export const API_CANDIDATE_ROOT = '/candidates';
export const API_VACANCY_ROOT = '/vacancies';
export const API_COMPANY_ROOT = '/companies';
export const API_RECRUITER_ROOT = '/recruiters';
export const API_CITIES_ENUMS = '/enums/cities';
export const API_SCHOOLS_ENUMS = '/enums/su';
export const API_UNIVERSITY_ENUMS = '/enums/su';
// export const API_SCHOOLS_ENUMS = '/enums/schools';
// export const API_UNIVERSITY_ENUMS = '/enums/univers';
export const API_LOGIN = '/authentication/login';
export const API_LOGOUT = '/authentication/logout';
export const API_FORGOT_PASSWORD = '/password/restore';
export const API_IMAGES = '/images';
export const API_FILES = '/files';
export const API_ALL_JOBS = '/jobs';
export const API_OPEN_JOBS = '/vacancies?status=opened';
export const API_DRAFT_JOBS = '/vacancies?status=draft';
export const API_CLOSED_JOBS = '/vacancies?status=closed';
export const API_ALL_MATCHES = '/matches';
export const API_BOOKMARKED_MATCHES = '/matches';
export const API_NOT_INTERESTED_MATCHES = '/matches';
export const API_GET_USER_SESSION = '/users/current';
export const API_CLEAN_SESSION_MESSAGE = '/users/clean';
export const API_CHANGE_PASSWORD = '/password/change';
export const RESEND_TOKEN_TO_EMAIL = '/users/resend/';
