export const SHOW_SUMMARY_HEAD_STANDARD = 'CANDIDATE_APPLICATION_SHOW_SUMMARY_HEAD_STANDARD'
export const SHOW_SUMMARY_HEAD_EDIT = 'CANDIDATE_APPLICATION_SHOW_SUMMARY_HEAD_EDIT'

export const ONBOARDING_TO_APPLICATION_MIGRATION = 'CANDIDATE_ONBOARDING_TO_APPLICATION_MIGRATION'

export const IMPORT_STARTED = 'CANDIDATE_APPLICATION_IMPORT_FROM_LINKEDIN_STARTED'
export const IMPORT_COMPLETED = 'CANDIDATE_APPLICATION_IMPORT_FROM_LINKEDIN_COMPLETED'

export const FETCH_LINKEDIN_DATA_REQUESTED = 'CANDIDATE_APPLICATION_FETCH_LINKEDIN_DATA_REQUESTED'
export const FETCH_LINKEDIN_DATA_SUCCEEDED = 'CANDIDATE_APPLICATION_FETCH_LINKEDIN_DATA_SUCCEEDED'
export const FETCH_LINKEDIN_DATA_FAILED = 'CANDIDATE_APPLICATION_FETCH_LINKEDIN_DATA_FAILED'

export const SAVE_SUMMARY_DATA = 'CANDIDATE_APPLICATION_SAVE_SUMMARY_DATA'
export const SAVE_SUMMARY_DATA_SUCCEEDED = 'CANDIDATE_APPLICATION_SAVE_SUMMARY_DATA_SUCCEEDED'
export const SAVE_SUMMARY_DATA_FAILED = 'CANDIDATE_APPLICATION_SAVE_SUMMARY_DATA_FAILED'

export const SHOW_ACCORDION = 'CANDIDATE_APPLICATION_SHOW_ACCORDION'

export const PROFILE_PHOTO_STEP = 'CANDIDATE_APPLICATION_PROFILE_PHOTO_STEP'
export const SAVE_PROFILE_PHOTO_DATA = 'CANDIDATE_APPLICATION_SAVE_PROFILE_PHOTO_DATA'

export const EXPERIENCE_STEP = 'CANDIDATE_APPLICATION_EXPERIENCE_STEP'
export const SHOW_EXPERIENCE_STEP = 'CANDIDATE_APPLICATION_SHOW_EXPERIENCE_STEP'
export const SAVE_EXPERIENCE_DATA = 'CANDIDATE_APPLICATION_SAVE_EXPERIENCE_DATA'
export const CLOSE_EXPERIENCE_STEP = 'CANDIDATE_APPLICATION_CLOSE_EXPERIENCE_STEP'

export const EDUCATION_STEP = 'CANDIDATE_APPLICATION_EDUCATION_STEP'
export const SHOW_EDUCATION_STEP = 'CANDIDATE_APPLICATION_SHOW_EDUCATION_STEP'
export const SAVE_EDUCATION_DATA = 'CANDIDATE_APPLICATION_SAVE_EDUCATION_DATA'
export const CLOSE_EDUCATION_STEP = 'CANDIDATE_APPLICATION_CLOSE_EDUCATION_STEP'

export const LOCATION_STEP = 'CANDIDATE_APPLICATION_LOCATION_STEP'
export const SHOW_LOCATION_STEP = 'CANDIDATE_APPLICATION_SHOW_LOCATION_STEP'
export const SAVE_LOCATION_DATA = 'CANDIDATE_APPLICATION_SAVE_LOCATION_DATA'
export const CLOSE_LOCATION_STEP = 'CANDIDATE_APPLICATION_CLOSE_LOCATION_STEP'

export const SOCIAL_MEDIA_STEP = 'CANDIDATE_APPLICATION_SOCIAL_MEDIA_STEP'
export const SHOW_SOCIAL_MEDIA_STEP = 'CANDIDATE_APPLICATION_SHOW_SOCIAL_MEDIA_STEP'
export const SAVE_SOCIAL_MEDIA_DATA = 'CANDIDATE_APPLICATION_SAVE_SOCIAL_MEDIA_DATA'
export const CLOSE_SOCIAL_MEDIA_STEP = 'CANDIDATE_APPLICATION_CLOSE_SOCIAL_MEDIA_STEP'

export const SKILLS_STEP = 'CANDIDATE_APPLICATION_SKILLS_STEP'
export const SHOW_SKILLS_STEP = 'CANDIDATE_APPLICATION_SHOW_SKILLS_STEP'
export const SAVE_SKILLS_DATA = 'CANDIDATE_APPLICATION_SAVE_SKILLS_DATA'
export const CLOSE_SKILLS_STEP = 'CANDIDATE_APPLICATION_CLOSE_SKILLS_STEP'

export const INTERESTS_STEP = 'CANDIDATE_APPLICATION_INTERESTS_STEP'
export const SHOW_INTERESTS_STEP = 'CANDIDATE_APPLICATION_SHOW_INTERESTS_STEP'
export const SAVE_INTERESTS_DATA = 'CANDIDATE_APPLICATION_SAVE_INTERESTS_DATA'
export const SAVE_INTERESTS_PHOTO = 'CANDIDATE_APPLICATION_SAVE_INTERESTS_PHOTO'
export const CLOSE_INTERESTS_STEP = 'CANDIDATE_APPLICATION_CLOSE_INTERESTS_STEP'

export const GET_LATEST_PROFILE = 'CANDIDATE_APPLICATION_GET_LATEST_PROFILE'
export const FILL_IN_PROFILE = 'CANDIDATE_APPLICATION_FILL_IN_PROFILE'

export const SET_DEFAULT_STATE = 'CANDIDATE_APPLICATION_SET_DEFAULT_STATE'

export const STARTUP_COMPLETED_STEPS = 5
