export const SHOW_SUMMARY_HEAD_STANDARD = 'COMPANY_APPLICATION_SHOW_SUMMARY_HEAD_STANDARD'
export const SHOW_SUMMARY_HEAD_EDIT = 'COMPANY_APPLICATION_SHOW_SUMMARY_HEAD_EDIT'

export const ONBOARDING_TO_APPLICATION_MIGRATION = 'COMPANY_ONBOARDING_TO_APPLICATION_MIGRATION'

export const IMPORT_STARTED = 'COMPANY_APPLICATION_IMPORT_FROM_LINKEDIN_STARTED'
export const IMPORT_COMPLETED = 'COMPANY_APPLICATION_IMPORT_FROM_LINKEDIN_COMPLETED'

export const FETCH_LINKEDIN_DATA_REQUESTED = 'COMPANY_APPLICATION_FETCH_LINKEDIN_DATA_REQUESTED'
export const FETCH_LINKEDIN_DATA_SUCCEEDED = 'COMPANY_APPLICATION_FETCH_LINKEDIN_DATA_SUCCEEDED'
export const FETCH_LINKEDIN_DATA_FAILED = 'COMPANY_APPLICATION_FETCH_LINKEDIN_DATA_FAILED'

export const SAVE_SUMMARY_DATA = 'COMPANY_APPLICATION_SAVE_SUMMARY_DATA'
export const SAVE_SUMMARY_DATA_SUCCEEDED = 'COMPANY_APPLICATION_SAVE_SUMMARY_DATA_SUCCEEDED'
export const SAVE_SUMMARY_DATA_FAILED = 'COMPANY_APPLICATION_SAVE_SUMMARY_DATA_FAILED'

export const SAVE_PROFILE_PHOTO_DATA = 'COMPANY_APPLICATION_SAVE_PROFILE_PHOTO_DATA'

export const SHOW_ACCORDION = 'COMPANY_APPLICATION_SHOW_ACCORDION'

export const PROFILE_PHOTO_STEP = 'COMPANY_APPLICATION_PROFILE_PHOTO_STEP'

export const SOCIAL_MEDIA_STEP = 'COMPANY_APPLICATION_SOCIAL_MEDIA_STEP'
export const SHOW_SOCIAL_MEDIA_STEP = 'COMPANY_APPLICATION_SHOW_SOCIAL_MEDIA_STEP'
export const SAVE_SOCIAL_MEDIA_DATA = 'COMPANY_APPLICATION_SAVE_SOCIAL_MEDIA_DATA'
export const CLOSE_SOCIAL_MEDIA_STEP = 'COMPANY_APPLICATION_CLOSE_SOCIAL_MEDIA_STEP'

export const LOCATION_STEP = 'COMPANY_APPLICATION_LOCATION_STEP'
export const SHOW_LOCATION_STEP = 'COMPANY_APPLICATION_SHOW_LOCATION_STEP'
export const SAVE_LOCATION_DATA = 'COMPANY_APPLICATION_SAVE_LOCATION_DATA'
export const CLOSE_LOCATION_STEP = 'COMPANY_APPLICATION_CLOSE_LOCATION_STEP'

export const PERSIST_TEMP_OFFICES = 'COMPANY_APPLICATION_PERSIST_TEMP_OFFICES'
export const SET_CITY_AND_STATE_TO_OFFICE = 'COMPANY_APPLICATION_SET_CITY_AND_STATE_TO_OFFICE'

export const DESCRIPTION_STEP = 'COMPANY_APPLICATION_DESCRIPTION_STEP'
export const SHOW_DESCRIPTION_STEP = 'COMPANY_APPLICATION_SHOW_DESCRIPTION_STEP'
export const SAVE_DESCRIPTION_DATA = 'COMPANY_APPLICATION_SAVE_DESCRIPTION_DATA'
export const CLOSE_DESCRIPTION_STEP = 'COMPANY_APPLICATION_CLOSE_DESCRIPTION_STEP'

export const QUOTE_OR_MOTTO_STEP = 'COMPANY_APPLICATION_QUOTE_OR_MOTTO_STEP'
export const SHOW_QUOTE_OR_MOTTO_STEP = 'COMPANY_APPLICATION_SHOW_QUOTE_OR_MOTTO_STEP'
export const SAVE_QUOTE_OR_MOTTO_DATA = 'COMPANY_APPLICATION_SAVE_QUOTE_OR_MOTTO_DATA'
export const CLOSE_QUOTE_OR_MOTTO_STEP = 'COMPANY_APPLICATION_CLOSE_QUOTE_OR_MOTTO_STEP'

export const PHOTO_STEP = 'COMPANY_APPLICATION_PHOTO_STEP'
export const SHOW_PHOTO_STEP = 'COMPANY_APPLICATION_SHOW_PHOTO_STEP'
export const SAVE_COMPANY_PHOTO = 'COMPANY_APPLICATION_SAVE_COMPANY_PHOTO'
export const SAVE_PHOTO_STEP = 'COMPANY_APPLICATION_SAVE_PHOTO_STEP'
export const CLOSE_PHOTO_STEP = 'COMPANY_APPLICATION_CLOSE_PHOTO_STEP'
export const REMOVE_COMPANY_PHOTO = 'COMPANY_APPLICATION_REMOVE_COMPANY_PHOTO'

export const SET_DEFAULT_STATE = 'COMPANY_APPLICATION_SET_DEFAULT_STATE'

export const GET_LATEST_PROFILE = 'COMPANY_APPLICATION_GET_LATEST_PROFILE'
export const FILL_IN_PROFILE_SUCCEEDED = 'COMPANY_APPLICATION_FILL_IN_PROFILE_SUCCEEDED'
export const FILL_IN_PROFILE_FAILED = 'COMPANY_APPLICATION_FILL_IN_PROFILE_FAILED'

export const STARTUP_COMPLETED_STEPS = 6

export const APPLICATION_UPDATE_COMPANY_SUCCEEDED = 'APPLICATION_UPDATE_COMPANY_SUCCEEDED'
export const APPLICATION_UPDATE_COMPANY_FAILED = 'APPLICATION_UPDATE_COMPANY_FAILED'

export const APPLICATION_UPDATE_RECRUITER_SUCCEEDED = 'APPLICATION_UPDATE_RECRUITER_SUCCEEDED'
export const APPLICATION_UPDATE_RECRUITER_FAILED = 'APPLICATION_UPDATE_RECRUITER_FAILED'
