export const AUTHENTICATION_CANDIDATE_REQUESTED = 'AUTHENTICATION_CANDIDATE_REQUESTED';
export const AUTHENTICATION_CANDIDATE_SUCCEEDED = 'AUTHENTICATION_CANDIDATE_SUCCEEDED';
export const AUTHENTICATION_CANDIDATE_FAILED = 'AUTHENTICATION_CANDIDATE_FAILED';

export const AUTHENTICATION_COMPANY_REQUESTED = 'AUTHENTICATION_COMPANY_REQUESTED';
export const AUTHENTICATION_COMPANY_SUCCEEDED = 'AUTHENTICATION_COMPANY_SUCCEEDED';
export const AUTHENTICATION_COMPANY_FAILED = 'AUTHENTICATION_COMPANY_FAILED';

export const AUTHENTICATION_REQUESTED = 'AUTHENTICATION_REQUESTED';
export const AUTHENTICATION_SUCCEEDED = 'AUTHENTICATION_SUCCEEDED';
export const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED';

export const USER_LOGOUT_REQUESTED = 'USER_LOGOUT_REQUESTED';
export const USER_LOGOUT_SUCCEEDED = 'USER_LOGOUT_SUCCEEDED';
export const USER_LOGOUT_FAILED = 'USER_LOGOUT_FAILED';

export const LOGIN_AT_BEGIN = 'LOGIN_AT_BEGIN';

export const CHANGE_PASSWORD_SUCCEEDED = 'CHANGE_PASSWORD_SUCCEEDED';
export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_FAILED = 'CHANGE_PASSWORD_FAILED';

export const FORGOT_PASSWORD_SUCCEEDED = 'FORGOT_PASSWORD_SUCCEEDED';
export const RESEND_TOKEN_SUCCEEDED = 'RESEND_TOKEN_SUCCEEDED';

export const RESOLVE_USER_SUCCEEDED = 'RESOLVE_USER_SUCCEEDED'
export const RESOLVE_USER_FAILED = 'RESOLVE_USER_FAILED'
