export const MATCHES_FETCH_SUCCEEDED = 'CANDIDATE_MATCHES_ALL_FETCH_SUCCEEDED';
export const BOOKMARKED_FETCH_SUCCEEDED = 'CANDIDATE_MATCHES_BOOKMARKED_FETCH_SUCCEEDED';

export const NOT_INTERESTED_FETCH_REQUESTED = 'CANDIDATE_MATCHES_NOT_INTERESTED_FETCH_REQUESTED';
export const NOT_INTERESTED_FETCH_SUCCEEDED = 'CANDIDATE_MATCHES_NOT_INTERESTED_FETCH_SUCCEEDED';
export const NOT_INTERESTED_FETCH_FAILED = 'CANDIDATE_MATCHES_NOT_INTERESTED_FETCH_FAILED';

export const ROUTE_TO_ALL = 'CANDIDATE_MATCHES_ROUTE_TO_ALL';
export const ROUTE_TO_BOOKMARKED = 'CANDIDATE_MATCHES_ROUTE_TO_BOOKMARKED';
export const ROUTE_TO_NOT_INTERESTED = 'CANDIDATE_MATCHES_ROUTE_TO_NOT_INTERESTED';

export const ALL_TAB = 'CANDIDATE_MATCHES_ALL_TAB';
export const BOOKMARKED_TAB = 'CANDIDATE_MATCHES_BOOKMARKED_TAB';
export const NOT_INTERESTED_TAB = 'CANDIDATE_MATCHES_NOT_INTERESTED_TAB';

export const SET_DEFAULT_STATE = 'CANDIDATE_MATCHES_SET_DEFAULT';
