export const SHOW_CONTACT_INFO_STEP = 'CANDIDATE_ONBOARDING_SHOW_CONTACT_INFO_STEP'
export const EMAIL_VALIDATE_REQUESTED = 'CANDIDATE_ONBOARDING_EMAIL_VALIDATE_REQUESTED'
export const EMAIL_ALREADY_REGISTERED = 'CANDIDATE_ONBOARDING_EMAIL_ALREADY_REGISTERED'
export const EMAIL_VALIDATE_SUCCEEDED = 'CANDIDATE_ONBOARDING_EMAIL_VALIDATE_SUCCEEDED'
export const SAVE_CONTACT_INFO_DATA = 'CANDIDATE_ONBOARDING_SAVE_CONTACT_INFO_DATA'

export const SHOW_INDUSTRY_STEP = 'CANDIDATE_ONBOARDING_SHOW_INDUSTRY_STEP'
export const SAVE_INDUSTRY_DATA = 'CANDIDATE_ONBOARDING_SAVE_INDUSTRY_DATA'

export const SHOW_FIELD_OF_EXPERTISE_STEP = 'CANDIDATE_ONBOARDING_SHOW_FIELD_OF_EXPERTISE_STEP'
export const SAVE_FIELD_OF_EXPERTISE_DATA = 'CANDIDATE_ONBOARDING_SAVE_FIELD_OF_EXPERTISE_DATA'

export const SHOW_JOB_TITLE_STEP = 'CANDIDATE_ONBOARDING_SHOW_JOB_TITLE_STEP'
export const SAVE_JOB_TITLE_DATA = 'CANDIDATE_ONBOARDING_SAVE_JOB_TITLE_DATA'

export const SHOW_INCOME_STEP = 'CANDIDATE_ONBOARDING_SHOW_INCOME_STEP'
export const SAVE_INCOME_DATA = 'CANDIDATE_ONBOARDING_SAVE_INCOME_DATA'

export const SHOW_VALUES_STEP = 'CANDIDATE_ONBOARDING_SHOW_VALUES_STEP'
export const SAVE_VALUES_DATA = 'CANDIDATE_ONBOARDING_SAVE_VALUES_DATA'

export const SHOW_EXPERIENCE_STEP = 'CANDIDATE_ONBOARDING_SHOW_EXPERIENCE_STEP'
export const SAVE_EXPERIENCE_DATA = 'CANDIDATE_ONBOARDING_SAVE_EXPERIENCE_DATA'

export const SHOW_APPLICATION_STEP = 'CANDIDATE_ONBOARDING_SHOW_APPLICATION_STEP'
export const SAVE_APPLICATION_DATA = 'CANDIDATE_ONBOARDING_SAVE_APPLICATION_DATA'

export const SHOW_SET_UP_PASSWORD_STEP = 'CANDIDATE_ONBOARDING_SHOW_SET_UP_PASSWORD_STEP'
export const SAVE_SET_UP_PASSWORD_DATA = 'CANDIDATE_ONBOARDING_SAVE_SET_UP_PASSWORD_DATA'

export const APPLY_FOR_MEMBERSHIP_REQUESTED = 'CANDIDATE_ONBOARDING_APPLY_FOR_MEMBERSHIP_REQUESTED'
export const APPLY_FOR_MEMBERSHIP_SUCCEEDED = 'CANDIDATE_ONBOARDING_APPLY_FOR_MEMBERSHIP_SUCCEEDED'
export const APPLY_FOR_MEMBERSHIP_FAILED = 'CANDIDATE_ONBOARDING_APPLY_FOR_MEMBERSHIP_FAILED'

export const THIS_EMAIL_IS_ALREADY_REGISTERED = 'This email is already registered'

export const INDUSTRY_DROPDOWN_DATA = []
export const VALUE_ASSESSMENTS_DROPDOWN_DATA = []
export const FIELD_OF_EXPERTISE_DROPDOWN_DATA = []
export const JOB_TITLE_DROPDOWN_DATA = []
export const ANNUAL_INCOME_DROPDOWN_DATA = []
export const EXPERIENCE_DROPDOWN_DATA = []
export const DEGREE_DROPDOWN_DATA = []
