export const SHOW_CONTACT_INFO_STEP = 'COMPANY_ONBOARDING_SHOW_CONTACT_INFO_STEP'
export const EMAIL_VALIDATE_REQUESTED = 'COMPANY_ONBOARDING_EMAIL_VALIDATE_REQUESTED'
export const EMAIL_ALREADY_REGISTERED = 'COMPANY_ONBOARDING_EMAIL_ALREADY_REGISTERED'
export const EMAIL_VALIDATE_SUCCEEDED = 'COMPANY_ONBOARDING_EMAIL_VALIDATE_SUCCEEDED'
export const SAVE_CONTACT_INFO_DATA = 'COMPANY_ONBOARDING_SAVE_CONTACT_INFO_DATA'

export const SHOW_COMPANY_TYPE_STEP = 'COMPANY_ONBOARDING_SHOW_COMPANY_TYPE_STEP'
export const SAVE_COMPANY_TYPE_DATA = 'COMPANY_ONBOARDING_SAVE_COMPANY_TYPE_DATA'

export const SHOW_HEADQUARTERS_LOCATION_STEP = 'COMPANY_ONBOARDING_SHOW_HEADQUARTERS_LOCATION_STEP'
export const SAVE_HEADQUARTERS_LOCATION_DATA = 'COMPANY_ONBOARDING_SAVE_HEADQUARTERS_LOCATION_DATA'

export const SHOW_NUMBER_OF_EMPLOYEES_STEP = 'COMPANY_ONBOARDING_SHOW_NUMBER_OF_EMPLOYEES_STEP'
export const SAVE_NUMBER_OF_EMPLOYEES_DATA = 'COMPANY_ONBOARDING_SAVE_NUMBER_OF_EMPLOYEES_DATA'

export const SHOW_FOUNDATION_YEAR_STEP = 'COMPANY_ONBOARDING_SHOW_FOUNDATION_YEAR_STEP'
export const SAVE_FOUNDATION_YEAR_DATA = 'COMPANY_ONBOARDING_SAVE_FOUNDATION_YEAR_DATA'

export const SHOW_WEBSITE_AND_SOCIAL_MEDIA_STEP = 'COMPANY_ONBOARDING_SHOW_WEBSITE_AND_SOCIAL_MEDIA_STEP'
export const SAVE_WEBSITE_AND_SOCIAL_MEDIA_DATA = 'COMPANY_ONBOARDING_SAVE_WEBSITE_AND_SOCIAL_MEDIA_DATA'

export const SHOW_VALUES_STEP = 'COMPANY_ONBOARDING_SHOW_VALUES_STEP'
export const SAVE_VALUES_DATA = 'COMPANY_ONBOARDING_SAVE_VALUES_DATA'

export const SHOW_SET_UP_PASSWORD_STEP = 'COMPANY_ONBOARDING_SHOW_SET_UP_PASSWORD_STEP'
export const SAVE_SET_UP_PASSWORD_DATA = 'COMPANY_ONBOARDING_SAVE_SET_UP_PASSWORD_DATA'

export const SHOW_DEFAULT_STEP = SHOW_CONTACT_INFO_STEP

export const APPLY_FOR_MEMBERSHIP_REQUESTED = 'COMPANY_ONBOARDING_APPLY_FOR_MEMBERSHIP_REQUESTED'
export const APPLY_FOR_MEMBERSHIP_SUCCEEDED = 'COMPANY_ONBOARDING_APPLY_FOR_MEMBERSHIP_SUCCEEDED'
export const APPLY_FOR_MEMBERSHIP_FAILED = 'COMPANY_ONBOARDING_APPLY_FOR_MEMBERSHIP_FAILED'

export const THIS_EMAIL_IS_ALREADY_REGISTERED = 'This email is already registered'
export const THIS_COMPANY_IS_ALREADY_REGISTERED = 'This company is already registered'

export const COMPANY_TYPE_DATA = []
export const COMPANY_EMPLOYEES_DATA = []
export const VALUE_ASSESSMENTS_DROPDOWN_DATA = []
