export const FETCH_JOBS_REQUESTED = 'RECRUITER_FETCH_JOBS_REQUESTED'
export const FETCH_JOBS_SUCCEEDED = 'RECRUITER_FETCH_JOBS_SUCCEEDED'
export const FETCH_JOBS_FAILED = 'RECRUITER_FETCH_JOBS_FAILED'

export const FETCH_COMPANY_REQUESTED = 'RECRUITER_FETCH_COMPANY_REQUESTED'
export const FETCH_COMPANY_SUCCEEDED = 'RECRUITER_FETCH_COMPANY_SUCCEEDED'
export const FETCH_COMPANY_FAILED = 'RECRUITER_FETCH_COMPANY_FAILED'

export const FETCH_RECRUITER_REQUESTED = 'RECRUITER_FETCH_RECRUITER_REQUESTED'
export const FETCH_RECRUITER_SUCCEEDED = 'RECRUITER_FETCH_RECRUITER_SUCCEEDED'
export const FETCH_RECRUITER_FAILED = 'RECRUITER_FETCH_RECRUITER_FAILED'

export const FETCH_MATCHES_REQUESTED = 'RECRUITER_FETCH_MATCHES_REQUESTED'
export const FETCH_MATCHES_SUCCEEDED = 'RECRUITER_FETCH_MATCHES_SUCCEEDED'
export const FETCH_MATCHES_FAILED = 'RECRUITER_FETCH_MATCHES_FAILED'

export const FETCH_CANDIDATE_REQUESTED = 'RECRUITER_FETCH_CANDIDATE_REQUESTED'
export const FETCH_CANDIDATE_SUCCEEDED = 'RECRUITER_FETCH_CANDIDATE_SUCCEEDED'
export const FETCH_CANDIDATE_FAILED = 'RECRUITER_FETCH_CANDIDATE_FAILED'


export const ROUTE_TO_OPEN = 'COMPANY_JOBS_ROUTE_TO_OPEN'
export const ROUTE_TO_DRAFTS = 'COMPANY_JOBS_ROUTE_TO_DRAFTS'
export const ROUTE_TO_CLOSED = 'COMPANY_JOBS_ROUTE_TO_CLOSED'

export const OPEN_TAB = 'COMPANY_JOBS_OPEN_TAB'
export const DRAFTS_TAB = 'COMPANY_JOBS_DRAFTS_TAB'
export const CLOSED_TAB = 'COMPANY_JOBS_CLOSED_TAB'

export const EMPLOYEMENTS_DROPDOWN_DATA = [];
export const DEGREES_DROPDOWN_DATA = [];
export const CLOSE_JOB_SUCCEEDED = 'COMPANY_JOBS_CLOSE_JOB_SUCCEEDED';
export const DELETE_JOB_SUCCEEDED = 'COMPANY_JOBS_DELETE_JOB_SUCCEEDED';
export const OPEN_JOB_SUCCEEDED = 'COMPANY_JOBS_OPEN_JOB_SUCCEEDED';
export const CREATE_JOB_SUCCEEDED = "CREATE_JOB_SUCCEEDED"
export const CREATE_JOB_FAILED = "CREATE_JOB_FAILED"

export const UPDATE_JOB_SUCCEEDED = "UPDATE_JOB_SUCCEEDED"
export const UPDATE_JOB_FAILED = "UPDATE_JOB_FAILED"

export const UPDATE_COMPANY_SUCCEEDED = "UPDATE_COMPANY_SUCCEEDED"
export const UPDATE_COMPANY_FAILED = "UPDATE_COMPANY_FAILED"

export const UPDATE_RECRUITER_SUCCEEDED = "UPDATE_RECRUITER_SUCCEEDED"
export const UPDATE_RECRUITER_FAILED = "UPDATE_RECRUITER_FAILED"

export const REJECT_POST_SUCCEEDED = 'RECRUITER_MATCHES_REJECT_POST_SUCCEEDED';
export const APPROVE_POST_SUCCEEDED = 'RECRUITER_MATCHES_APPROVE_POST_SUCCEEDED';
export const RESTORE_POST_SUCCEEDED = 'RECRUITER_MATCHES_RESTORE_POST_SUCCEEDED';

export const OPEN_APPROVE_AND_EMAIL = 'RECRUITER_OPEN_APPROVE_AND_EMAIL'
