export const FETCH_JOBS_REQUESTED = 'RECRUITER_FETCH_JOBS_REQUESTED'
export const FETCH_JOBS_SUCCEEDED = 'RECRUITER_FETCH_JOBS_SUCCEEDED'
export const FETCH_JOBS_FAILED = 'RECRUITER_FETCH_JOBS_FAILED'

export const FETCH_COMPANY_REQUESTED = 'RECRUITER_FETCH_COMPANY_REQUESTED'
export const FETCH_COMPANY_SUCCEEDED = 'RECRUITER_FETCH_COMPANY_SUCCEEDED'
export const FETCH_COMPANY_FAILED = 'RECRUITER_FETCH_COMPANY_FAILED'

export const FETCH_RECRUITER_REQUESTED = 'RECRUITER_FETCH_RECRUITER_REQUESTED'
export const FETCH_RECRUITER_SUCCEEDED = 'RECRUITER_FETCH_RECRUITER_SUCCEEDED'
export const FETCH_RECRUITER_FAILED = 'RECRUITER_FETCH_RECRUITER_FAILED'


// export const OPEN_FETCH_REQUESTED = 'COMPANY_JOBS_OPEN_FETCH_REQUESTED'
// export const OPEN_FETCH_SUCCEEDED = 'COMPANY_JOBS_OPEN_FETCH_SUCCEEDED'
// export const OPEN_FETCH_FAILED = 'COMPANY_JOBS_OPEN_FETCH_FAILED'
//
// export const DRAFTS_FETCH_REQUESTED = 'COMPANY_JOBS_DRAFTS_FETCH_REQUESTED'
// export const DRAFTS_FETCH_SUCCEEDED = 'COMPANY_JOBS_DRAFTS_FETCH_SUCCEEDED'
// export const DRAFTS_FETCH_FAILED = 'COMPANY_JOBS_DRAFTS_FETCH_FAILED'
//
// export const CLOSED_FETCH_REQUESTED = 'COMPANY_JOBS_CLOSED_FETCH_REQUESTED'
// export const CLOSED_FETCH_SUCCEEDED = 'COMPANY_JOBS_CLOSED_FETCH_SUCCEEDED'
// export const CLOSED_FETCH_FAILED = 'COMPANY_JOBS_CLOSED_FETCH_FAILED'

export const ROUTE_TO_OPEN = 'COMPANY_JOBS_ROUTE_TO_OPEN'
export const ROUTE_TO_DRAFTS = 'COMPANY_JOBS_ROUTE_TO_DRAFTS'
export const ROUTE_TO_CLOSED = 'COMPANY_JOBS_ROUTE_TO_CLOSED'

export const OPEN_TAB = 'COMPANY_JOBS_OPEN_TAB'
export const DRAFTS_TAB = 'COMPANY_JOBS_DRAFTS_TAB'
export const CLOSED_TAB = 'COMPANY_JOBS_CLOSED_TAB'

export const EMPLOYEMENTS_DROPDOWN_DATA = [];
export const DEGREES_DROPDOWN_DATA = [];

// export const SHOW_SUMMARY_HEAD_STANDARD = 'COMPANY_JOBS_SHOW_SUMMARY_HEAD_STANDARD'
// export const SHOW_SUMMARY_HEAD_EDIT = 'COMPANY_JOBS_SHOW_SUMMARY_HEAD_EDIT'
//
// export const SAVE_SUMMARY_DATA = 'COMPANY_JOBS_SAVE_SUMMARY_DATA'
// export const SAVE_SUMMARY_DATA_SUCCEEDED = 'COMPANY_JOBS_SAVE_SUMMARY_DATA_SUCCEEDED'
// export const SAVE_SUMMARY_DATA_FAILED = 'COMPANY_JOBS_SAVE_SUMMARY_DATA_FAILED'
//
// export const DESCRIPTION_STEP = 'COMPANY_JOBS_DESCRIPTION_STEP'
// export const SHOW_DESCRIPTION_STEP = 'COMPANY_JOBS_SHOW_DESCRIPTION_STEP'
// export const SAVE_DESCRIPTION_DATA = 'COMPANY_JOBS_SAVE_DESCRIPTION_DATA'
// export const CLOSE_DESCRIPTION_STEP = 'COMPANY_JOBS_CLOSE_DESCRIPTION_STEP'
//
// export const RESPONSIBILITIES_STEP = 'COMPANY_JOBS_RESPONSIBILITIES_STEP'
// export const SHOW_RESPONSIBILITIES_STEP = 'COMPANY_JOBS_SHOW_RESPONSIBILITIES_STEP'
// export const SAVE_RESPONSIBILITIES_DATA = 'COMPANY_JOBS_SAVE_RESPONSIBILITIES_DATA'
// export const CLOSE_RESPONSIBILITIES_STEP = 'COMPANY_JOBS_CLOSE_RESPONSIBILITIES_STEP'
//
// export const SKILLS_AND_REQUIREMENTS_STEP = 'COMPANY_JOBS_SKILLS_AND_REQUIREMENTS_STEP'
// export const SHOW_SKILLS_AND_REQUIREMENTS_STEP = 'COMPANY_JOBS_SHOW_SKILLS_AND_REQUIREMENTS_STEP'
// export const SAVE_SKILLS_AND_REQUIREMENTS_DATA = 'COMPANY_JOBS_SAVE_SKILLS_AND_REQUIREMENTS_DATA'
// export const CLOSE_SKILLS_AND_REQUIREMENTS_STEP = 'COMPANY_JOBS_CLOSE_SKILLS_AND_REQUIREMENTS_STEP'

export const CLOSE_JOB_SUCCEEDED = 'COMPANY_JOBS_CLOSE_JOB_SUCCEEDED';
export const DELETE_JOB_SUCCEEDED = 'COMPANY_JOBS_DELETE_JOB_SUCCEEDED';
export const OPEN_JOB_SUCCEEDED = 'COMPANY_JOBS_OPEN_JOB_SUCCEEDED';

// export const SET_DEFAULT_STATE = 'COMPANY_JOBS_SET_DEFAULT';
//
// export const SET_DEFAULT_NEW_JOB_STATE = 'COMPANY_JOBS_SET_DEFAULT_NEW_JOB_STATE';
// export const CLOSE_OPENED_NEW_JOB_CARD = 'COMPANY_JOBS_CLOSE_OPENED_NEW_JOB_CARD';

export const CREATE_JOB_SUCCEEDED = "CREATE_JOB_SUCCEEDED"
export const CREATE_JOB_FAILED = "CREATE_JOB_FAILED"

export const UPDATE_JOB_SUCCEEDED = "UPDATE_JOB_SUCCEEDED"
export const UPDATE_JOB_FAILED = "UPDATE_JOB_FAILED"
